version: "3"
services:
    nginx:
        build:
            dockerfile: Dockerfile
            context: ./nginx
        restart: always
        container_name: nginx
    api:
        build:
            dockerfile: Dockerfile
            context: ./api
        env_file:
            - ./api/.env
        depends_on:
            - postgres
        container_name: api
    client:
        build:
            dockerfile: Dockerfile
            context: ./client
        container_name: client
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=deger
            - POSTGRES_DB=chatdb
        volumes:
            - ./api/postgres-data:/var/lib/postgresql/data
        ports:
            - 5431:5432
        container_name: db

volumes:
    postgres-data:
networks:
    draw-rec-network:
        driver: bridge

